### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by ElodieBsq** [aarkilanian/bird-colour-gradient#2]
**General**

- [x] create the presentation (Powerpoint or whatever) @gladjo 

**Data extraction**
- [x] extract birds abundance from eBird for each park @aarkilanian 

- [x] calculate relative abundance for each  species in each park

- [x] make a dataset for each park (species, abundance, relative abundance)

**Scrapping**

- [x] scrape images for each species from Aubudun

**Colour  analysis**

- [x] do HSL colour analysis

- [ ] create one dataset  site for HSL analysis (location, species, abundance, H, S, L)

**Final dataset**

- [ ] separate HUE into 10(?) bin

- [ ] create one data set for HUE(location, proportion, bin(HUE))

- [ ] create one data set for mean HSL (location, mean saturation, mean luminosity, mean HUE)

**Creating figures**

- [x] Figure 1: map with all the parks @gladjo 

- [x] Figure2:  stack horizontal pie chart for color proportion per parks @cbautistaro 
<img src="https://user-images.githubusercontent.com/46568440/57166244-90fe1180-6dc7-11e9-9389-16c9b6181abc.png" width=150/>

- [x] Figure 3: distributions of HUE bins in function of parks gradient 
<img src="https://user-images.githubusercontent.com/46568440/57165250-8130fe00-6dc4-11e9-9c94-608069ae41b7.jpg" width=150/>

- [ ] Figure 4: color gradient with the map 
<img src="https://user-images.githubusercontent.com/46568440/57166179-5eecaf80-6dc7-11e9-8c58-874d66ca731d.png" width=150/> (MAYBE NOT)

- [x] ordination 3D plot @ElodieBsq  

**Statistical analysis**

- [x] explore statistcal analysis option  @cbautistaro
